version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: gil
      POSTGRES_PASSWORD: gil12345
      POSTGRES_DB: diciplinas
    volumes:
      - postgres_data:/var/lib/postgresql@16/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: